### ISSUE TITLE
GNOME 44 runtime available

### ISSUE THREAD

**Issue by JamiKettunen** [flathub/org.pipewire.Helvum#5]
Just saw this app on my shrinking `flatpak list --app-runtime=org.gnome.Platform//43` output, perhaps I'll even take a shot at updating the runtime myself if I'm not too busy.

**Comment by tom-a-wagner** [comment]
> Just saw this app on my shrinking `flatpak list --app-runtime=org.gnome.Platform//43` output, perhaps I'll even take a shot at updating the runtime myself if I'm not too busy.

Thanks for the reminder, I always forget. And yeah, feel free to open a Pull Request, updating should be too hard aside from maybe needing to switch to the latest LLVM and Rust Extensions

**Comment by hfiguiere** [comment]
> maybe needing to switch to the latest LLVM and Rust Extensions

it's the same base runtime so this shouldn't even be needed (llvm)
